# -*- coding: utf-8 -*-
"""visualization-project-laptop-sales_sol

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M53HHyac1sf2zjJ_UkB59movx5UKI0y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

"""# **#1 What is target market? Male or female?**"""

sales = pd.read_csv(r'/content/Sales_data.txt')
sales

# Comparing 'Profit' between male and female
total_profit = sales.groupby('Contact Sex')['Profit'].sum()
total_profit

"""1. The target marget seems to be males since their total profit of 2936.53 is higher than of females, which is 2522.48.

# **#2 If business is cash-constrained, which gender should be targeted?**
"""

# Let's look at the 'Our Cost' column

business_cost = sales.groupby('Contact Sex')['Our Cost'].sum()
business_cost

"""2. If the business is cash-constrained, they should probably target females more.

# **#3 If consumer is cash-constrained, which gender should be targeted?**
"""

# Let's look at the average price of 'Sale Price' grouped by gender
avg_consumer_cost = sales.groupby('Contact Sex')['Sale Price'].mean()
avg_consumer_cost

"""3. If the consumer is cash-constrained, males should be targeted.

# **#4 What is our target age to maximize profit?**
"""

# First consider the individual ages

individual_ages = sales.groupby('Contact Age')['Contact Age'].value_counts()
individual_ages

# Consider age ranges now
age_ranges_5 = sales.groupby('Contact Age')['Contact Age'].hist(bins = list(range(20, 61, 5))) # Increments of 5

age_ranges_10 = sales.groupby('Contact Age')['Contact Age'].hist(bins = list(range(20, 61, 10))) # Increments of 10

"""4. Considering the invididual age counts and age ranges, the business might consider targeting customers who are between 40 to 50 years old.

# **#5 Which product should we feature?**
"""

# Consider 'Profit' grouped by 'Prduct Type'
profit_by_prodtype = sales.groupby('Product Type')['Profit'].sum()
profit_by_prodtype

"""5. Since laptops yield the highest profit compared to desktops and tablets, the business should feature laptops.

# **#6 What lead sources have worked in the past: website, flyer, or email?**
"""

# Consider 'Profit' grouped by Lead Source
profit_by_leadsource = sales.groupby('Lead Source')['Profit'].sum()
profit_by_leadsource

"""6. The profit generated through Flyers 1, 2, 3, and 4 combined outyield profit genereated through email and website.

# **#7 When is the best time to do email marketing?**
"""

# First combine 'Sale Month' and 'Sale Year'
len(sales.columns) # Total columns 17 (0 to 16)

sales = sales.astype({'Sale Year':str}) # Convert 'Sale Year' to Object Type

sales['Month Year'] = sales['Sale Month'] + ' ' + sales['Sale Year'] # Combine 'Sale Month' and 'Sale Year'

sales['Month Year'] = pd.to_datetime(sales['Month Year'], format = '%B %Y') # Convert to datetime

months = sales.groupby('Lead Source')['Sale Month'].value_counts()
months

"""7. Since there were 2 sales acquired via email in November, perhaps the business might want to look into increasing its email marketing around November. They could also try including December as well since many shopping holidays (i.e. Thanksgiving, Black Friday, Cyber Monday, Christmas Eve, Christmas) occur towards the end of the year."""