# -*- coding: utf-8 -*-
"""visualization-project-laptop-sales_sol

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M53HHyac1sf2zjJ_UkB59movx5UKI0y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

"""# **#1 What is target market? Male or female?**"""

sales = pd.read_csv(r'/content/Sales_data.txt')
sales

# Comparing 'Profit' between male and female
total_profit = sales.groupby('Contact Sex')['Profit'].sum()
total_profit

"""1. The target marget seems to be males since their total profit of 2936.53 is higher than of females, which is 2522.48."""

# Example, sale price of $500, your cost is $300, and the shipping is $10.
# Case 1: You pass the shipping cost to the customer, so
# profit = (500 + 10) - $300 = 210
# Case 2: As the business, you take in the shipping cost
# profit = 500 - (300 + 10) = 190

"""# **#2 If business is cash-constrained, which gender should be targeted?**"""

# Let's see what happens if the business takes on the shipping cost
sales['Our Cost Plus Shipping'] = sales['Our Cost'] + sales['Shipping Cost']
business_cost2 = sales.groupby('Contact Sex')['Our Cost Plus Shipping'].sum()
business_cost2

# Consider the profit percentage given the business takes on the shipping cost
sales['Profit With Our Increased Cost'] = sales['Sale Price'] - sales['Our Cost Plus Shipping']
sales['Our Profit Percentage With Our Increased Cost'] = (sales['Profit With Our Increased Cost'] / sales['Our Cost Plus Shipping']) * 100
sales['Our Profit Percentage With Our Increased Cost']

sales.groupby('Contact Sex')['Our Profit Percentage With Our Increased Cost'].mean()

"""2. If the business is cash-constrained, they should target males.

# **#3 If consumer is cash-constrained, which gender should be targeted?**
"""

# Let's see what happens if the the customer takes on the shipping cost
sales['Sale Price Plus Shipping'] = sales['Sale Price'] + sales['Shipping Cost']
consumer_cost2 = sales.groupby('Contact Sex')['Sale Price Plus Shipping'].sum()
consumer_cost2

# Now consider the profit percentage given customers take on the shipping cost
# This gives the profit percentage per specific customer
sales['Profit With Their Increased Cost'] = sales['Sale Price Plus Shipping'] - sales['Our Cost']
sales['Our Profit Percentage With Their Increased Cost'] = (sales['Profit With Their Increased Cost'] / sales['Our Cost']) * 100
sales['Our Profit Percentage With Their Increased Cost']

# Net profit, grouped by sex
net_profit2 = sales.groupby('Contact Sex')['Profit With Their Increased Cost'].sum()
net_profit2

# Net cost, grouped by sex
net_cost2 = sales.groupby('Contact Sex')['Our Cost'].sum()
net_cost2

profit_percentage2 = net_profit2 / net_cost2
profit_percentage2.rename('Profit Percentage', inplace = True)

# Net profit percentage for all customers male and female
total_profit_percentage1 = (sales['Profit With Their Increased Cost'].sum() / sales['Our Cost'].sum()) * 100
total_profit_percentage1

"""3. If the consumer is cash-constrained, males should be targeted.

# **#4 What is our target age to maximize profit?**
"""

# First consider the individual ages

individual_ages = sales.groupby('Contact Age')['Contact Age'].value_counts()
individual_ages

ages = pd.cut(np.array(list(range(20, 61, 10))),10)
ages

# Consider age ranges now
age_ranges1 = sales.groupby('Contact Age')['Profit'].sum()

sales['Age Ranges'] = pd.cut(sales['Contact Age'], bins = range(20, 61, 5), right = False)
sales['Age Ranges']

sales.groupby('Age Ranges')['Profit'].sum().plot.bar()

"""4. Considering the invididual age counts and age ranges, the business might consider targeting customers who are between 45 (inclusive) to 50 years old (non-inclusive).

# **#5 Which product should we feature?**
"""

# Consider 'Profit' grouped by 'Prduct Type'
profit_by_prodtype = sales.groupby('Product Type')['Profit'].sum()
profit_by_prodtype

"""5. Since laptops yield the highest profit compared to desktops and tablets, the business should feature laptops.

# **#6 What lead sources have worked in the past: website, flyer, or email?**
"""

# Consider 'Profit' grouped by Lead Source
profit_by_leadsource = sales.groupby('Lead Source')['Profit'].sum()
profit_by_leadsource

"""6. The profit generated through Flyers 1, 2, 3, and 4 combined outyield profit genereated through email and website. However, if looking at the Flyers individually, then Website outyields the rest.

# **#7 When is the best time to do email marketing?**
"""

# Consider profit grouped by lead source and then sale month

profits_grouped = sales.groupby(['Lead Source', 'Sale Month'])['Profit'].sum()
profits_grouped

"""7. When looking at profits for each month where the lead source is Email, the company should consider increasing its marketing during November."""