# -*- coding: utf-8 -*-
"""reading-json-HW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZgKEJ4jktQzsRyOO4ulEjnq_Mg4IB1c
"""

# 1

import json

with open('/content/json_file.txt', 'r') as f:  #'r' we are only reading the file
  data = json.load(f)
data

for i in range(len(data)):
  for k, v in data[i].items(): # We're looking at each key-value pair in each entry of the list (b/c each entry is a dictionary)
      print(f"{k}: {v}")
  print(17*'=')

# 2

with open('/content/daily_covid_cases.json', 'r') as c:
  cases = json.load(c)
cases

cases.keys() # The 2 general keys are 'meta' and 'data'

cases['meta'].keys() # Under 'meta', the subkeys are 'build_time', 'license', 'version', and 'field_definitions'

cases['meta']['build_time']

cases['meta']['license']

cases['meta']['version']

cases['meta']['field_definitions']

cases['data'].keys()

cases['data']['cases']

# 2

# I decided to use .keys() earlier so I could find out what the exact keys were
# There were two main keys, and each of them had "subkeys"
# However, index-wise, I'm stuck on how to loop through the whole dictionary

for i in range(len(cases)):
  for k, v in cases[i].items():
    print(f"{k}: {v}")
  print('\n')