# -*- coding: utf-8 -*-
"""custom_datetimes_7312024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nipDlBhxU5ZE0yhOwXGPu86prRN7ui2u
"""

import datetime
import dateutil.parser
import pytz

# March 23, 2021

# date_1
date_1 = r'03/23/21'
format_1 = '%m/%d/%y'
date_1_obj = datetime.datetime.strptime(date_1, format_1)
print(date_1_obj)

# date_2
date_2 = r'23/03/2021'
format_2 = '%d/%m/%Y'
date_2_obj = datetime.datetime.strptime(date_2, format_2)
print(date_2_obj)

# date_3
date_3 = r'March 23rd, 2021 13:01 US/Pacific'
date_3_list = date_3.split()
USP_str = date_3_list[-1]
USP = pytz.timezone(USP_str)

date_3_fmtd = datetime.datetime.strptime(date_3, f"%B %drd, %Y %H:%M {USP}").astimezone(USP)
print(date_3_fmtd)


# date_4
date_4 = r'1:01pm 23rd March, 2021 Europe/London'
date_4_list = date_4.split()
EUL_str = date_4_list[-1]
EUL = pytz.timezone(EUL_str)

date_4_fmtd = datetime.datetime.strptime(date_4, f"%I:%M%p %drd %B, %Y {EUL}").astimezone(EUL)
print(date_4_fmtd)

# date_5
date_5 = 1616482800 # Epoch time
date_5_fmtd = datetime.datetime.fromtimestamp(date_5).strftime('%Y-%m-%d %H:%M:%S')
print(date_5_fmtd)

# date_6 # ISO 8601 format
date_6 = r'2021-03-23T12:00:53.034-07:00'
date_6_obj = datetime.datetime.fromisoformat(date_6)
print(date_6_obj)