# -*- coding: utf-8 -*-
"""stroke_analysis_7312024.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJXQWeJbj_yPeE3CMJSE0s7DImnQglma
"""

# I'm unsure about 9 and 10

#1
import pandas as pd
import numpy as np

stroke = pd.read_csv('/content/healthcare-dataset-stroke-data.csv')
stroke.describe()

#2
stroke_floats = stroke.select_dtypes("float64")
stroke_floats.describe()

#3

stroke_stroke = stroke.groupby('stroke')

#4

stroke_1 = stroke_stroke.get_group(1)
stroke_1

#5
stroke_stroke_float = stroke_1.select_dtypes("float64")
stroke_stroke_float.describe()

#6
stroke_int = stroke.select_dtypes("int64")
stroke_int.describe(percentiles=[]) # Append percentiles = []
# When I did percentiles = None, it displays the 25th, 50th, and 75th perecentiles
# However, when I do percentiles = [], it just displays the 50th percentile

#7
stroke_hyp_heart = stroke.groupby(['hypertension','heart_disease'])

#8
hyp1_heart1 = stroke_hyp_heart.get_group((1,1))
hyp1_heart1

#9
stroke_hyp_heart.count()[['id']]

#10
stroke.pivot_table(values = 'stroke', index = ['hypertension','heart_disease'], aggfunc = ["mean","std"])

#10 revised
stroke_hyp_heart['stroke'].agg("mean","std")