# -*- coding: utf-8 -*-
"""stroke_analysis_7312024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9cXw1vD13P643A1RhliXdu0ynA2R4wM
"""

# I'm unsure about 9 and 10

#1
import pandas as pd
import numpy as np

stroke = pd.read_csv('/content/healthcare-dataset-stroke-data.csv')
stroke

#2
stroke_floats = stroke.select_dtypes("float64")
stroke_floats.describe()

#3

stroke_stroke = stroke.groupby('stroke')

#4

stroke_1 = stroke_stroke.get_group(1)
stroke_1

#5
stroke_stroke_float = stroke_1.select_dtypes("float64")
stroke_stroke_float.describe()

#6
stroke_int = stroke.select_dtypes("int64")
stroke_int.describe()

#7
stroke_hyp_heart = stroke.groupby(['hypertension','heart_disease'])

#8
hyp1_heart1 = stroke_hyp_heart.get_group((1,1))
hyp1_heart1

#9
hyp1_heart1.count()

#10
stroke.pivot_table(values = 'stroke', index = ['hypertension','heart_disease'], aggfunc = ["mean","std"])