# -*- coding: utf-8 -*-
"""tmdb-api_solution

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAKT_SAwNoqC9Zn6F7i6qE4-HfemCTaJ

# **#1 and #2**
"""

!pip install tmdbsimple

import tmdbsimple as tmdb
import requests
import json
import pandas as pd
tmdb.API_KEY = 'b3ca90af8d6988fd6220149ce6a3235f'

search = tmdb.Search()
starWars = search.movie(query = 'Star Wars')
starWars

starWars.keys() # I just wanted to get a better view of the dictionary, so I
# investigated the keys first
# The keys are 'page', 'results', 'total_pages', and 'total_results'

"""# **#3**"""

starWars_df = pd.DataFrame(data = starWars['results']) # Data Frame
starWars_df

"""# **#4**"""

starWars_popularity = starWars_df.sort_values(by = 'popularity',ascending = False)
starWars_popularity